# Generated by Django 5.1.2 on 2024-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://res.cloudinary.com/db2agmwon/image/upload/v1722207114/profile-default.256x256_gdbltu.png', max_length=256),
        ),
    ]
