# Generated by Django 5.1.2 on 2024-10-22 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
